### PR TITLE
Added a PositiveAction Action to the MessagingServiceQuestion type.

### PR DESCRIPTION
**Pull request by jsauvexamarin**
Can be used like this:
var task = Application.Current?.MainPage?.DisplayAlert(info.Title, info.Question, info.Positive, info.Negative);
if (task != null && await task)
    info?.PositiveAction?.Invoke();

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
So I am thinking that actually it should have a OnResult, which returns the Positive or Negative probably a boolean is fine here and let's you make a decision based on it. 

Also, wondering if it should be an Action<bool> or a Fun<bool>

**Comment by jsauvexamarin** [comment]
You mean instead of only taking action on Positive? Instead, allowing dev to specify the action taken, whether Positive or Negative?

**Comment by jsauvexamarin** [comment]
I'd be cool with Action _or_ Func. My thought for Action is: at the point that I'm calling SendMessage, I already have access to all the values I'll need in order to take action when the user makes a decision.

**Comment by jamesmontemagno** [comment]
Yeah, that sounds good, i think just it should be Action<bool> that returns if it was positive or negative so you can respond.  If you implement that I can go ahead and merge in.

**Comment by jsauvexamarin** [comment]
I guess I'm not understanding. Since the DisplayAlert gets fired off by using the MessageService, then we essentially have no control over what happens with the result of the user decision. Wouldn't you have to setup a second pub/sub item with the MessagingService to communicate the result back to the original caller? If you just tuck an Action or a Func into the TArgs type, then it can be fired off in the subscriber, like this:

```
MessagingService.Current.Subscribe<MessagingServiceQuestion>(MessageKeys.DisplayQuestion, async (service, info) =>
{
    var task = Application.Current?.MainPage?.DisplayAlert(info.Title, info.Question, info.Positive, info.Negative);
    if (task != null && await task)
        info?.SuccessAction?.Invoke();
});
```

I dunno, maybe I'm missing something. Thoughts?

**Comment by jamesmontemagno** [comment]
So,

I would do this:

```
public Action<bool> OnCompleted { get; set; }


MessagingService.Current.Subscribe<MessagingServiceQuestion>(MessageKeys.DisplayQuestion, async (service, info) =>
{
    var task = Application.Current?.MainPage?.DisplayAlert(info.Title, info.Question, info.Positive, info.Negative);
    if (task == null)
      return;
   var result = await task;
    info?.OnCompleted?.Invoke(result);
});
```

I think this should also be added to the alert, but with just an public Action OnCompleted;

**Comment by jsauvexamarin** [comment]
Ahhh!! I dig. I'll wire it up and update the PR.

**Comment by jsauvexamarin** [comment]
And the usage can even be simplified to:

```
MessagingService.Current.Subscribe<MessagingServiceQuestion>(MessageKeys.DisplayQuestion, async (service, info) =>
{
    var task = Application.Current?.MainPage?.DisplayAlert(info.Title, info.Question, info.Positive, info.Negative);
    if (task == null)
      return;
    info?.OnCompleted?.Invoke(await task);
});
```

...placing the await task directly in the Invoke call, avoiding the var altogether. Pretty slick!

...or maybe even this:

```
MessagingService.Current.Subscribe<MessagingServiceQuestion>(MessageKeys.DisplayQuestion, async (service, info) =>
{
    var task = Application.Current?.MainPage?.DisplayAlert(info.Title, info.Question, info.Positive, info.Negative);
    if (task != null)
        info?.OnCompleted?.Invoke(await task);
});
```

**Comment by jamesmontemagno** [comment]
In your code make sure you actually do this:

```
if (task != null)
{
   var result = await task;
        info?.OnCompleted?.Invoke(result);
}
```

Because if any of those were null then your task would never get awaited!

**Comment by jsauvexamarin** [comment]
Oh, true!

**Pull request merged**
